### PR TITLE
capitalize JavaScript all the time

### LINKED ISSUE #193: JavaScript JIT isn't capitalized correctly in the page info panel
As can be seen in the attached screenshot the term "JavaScript" in "JavaScript JIT" isn't capitalized correctly in the page info panel. It's capitalized correctly everywhere else in the UI. 

Screenshot_20220620-111524

### PR DESCRIPTION
**Pull request by Reflux0301**
Per #193, JavaScript is trademarked, thus needing to be capitalized.

This also looks better than `javascript JIT`.

Should fix #193, needs testing.

### CODE REVIEW

**Comment by SkewedZeppelin** [comment]
Why did you add this as an additional patch instead of just editing the existing one?

**Comment by Reflux0301** [comment]
> Why did you add this as an additional patch instead of just editing the existing one?
> 
> https://github.com/GrapheneOS/Vanadium/blob/main/patches/0086-Implement-UI-for-JIT-site-settings.patch#L484

I will be 100% honest with you, I did not see that.

**Comment by thestinger** [comment]
This wording seems to be from upstream and we copied it. I don't think we should change it. You should suggest it for Chromium. I don't think we want to take on rebranding this kind of thing.

**Comment by thestinger** [comment]
All of the site settings use this style.

**Comment by Reflux0301** [comment]
> This wording seems to be from upstream and we copied it. I don't think we should change it. You should suggest it for Chromium. I don't think we want to take on rebranding this kind of thing.

Figured as much. Just wanted to try my luck downstream before going upstream.

> All of the site settings use this style.

While true, none of the terms are as specific as JavaScript. For example, location, microphone, camera, very generic. Although I agree this should be the behavior upstream, I'll work through that there. Thanks for the response.

**Pull request closed without merging**
