### PR TITLE
Use ShadowCallStack on arm64

### PR DESCRIPTION
**Pull request by loryeam**
This addresses #12. I'll report once the build is complete and tested.

### CODE REVIEW

**Comment by loryeam** [comment]
So far, I've been using it as my primary browser, seems to work fine. On GrapheneOS, only Vanadium webview is whitelisted. So, I probably won't be able to test webview on GrapheneOS, I'll setup up android studio VM for that.

Also, I can't seem to build `trichrome_chrome_bundle` target with this patch, it gives the error `clang++: error: unsupported option '-fsanitize=shadow-call-stack' for target 'arm-unknown-linux-android23'`. My guess is that it is trying to build 32-bit code with ShadowCallStack. I guess it won't be a problem if we only build 64-bit webview and browser. But GrapheneOS does include 32-bit webview, for compatibility reasons? I'll see if I can workaround this issue, this pull pull will remain draft until then.

**Comment by loryeam** [comment]
@flawedworld Correct me if I'm wrong (I haven't thorougly examined the GN files, so I could be wrong), this command (listed on [GrapheneOS website](https://grapheneos.org/build#browser-and-webview)) `ninja -C out/Default/ trichrome_webview_64_32_apk trichrome_chrome_64_32_apk trichrome_library_64_32_apk` will include 32-bit webview as per [this](https://source.chromium.org/chromium/chromium/src/+/main:chrome/android/BUILD.gn;l=3015).

**Comment by thestinger** [comment]
We make 64-bit builds with 32-bit WebView support for compatibility. Dropping 32-bit WebView support would break 32-bit only apps which use the WebView. We could potentially drop 32-bit WebView support... but it would make more sense to drop 32-bit support altogether on recent devices where that can be done.

**Comment by loryeam** [comment]
This should build now. Only thing that remains is testing. Since, the webview needs whitelisting and I can't build from source due to lack of powerful enough machine. I'll test this on emulator (I hope it doesn't require whitelisting there). I don't know which apps uses webview though, some help is appreciated.

**Comment by loryeam** [comment]
Unfortunately, as things stand right now. I'm unable to test the webview due to lack of proper testing device. So, I leave it upto you guys to do webview testing.

**Comment by Zanthed** [comment]
@loryeam Did this build successfully for you? And did testing it work on a real device (not emulator because it's not arm64)? Last time I tried doing this clang did not like this.

I was told `-ffixed-x18` is needed to get this building because ShadowCallStack uses the x18 register, but it may pose a compatibility issue because it's unclear what else may use the x18 register and cause things to break and crash that do use the x18 register because it's in use by Vanadium/WebView.

See https://clang.llvm.org/docs/ShadowCallStack.html#id6

**Comment by loryeam** [comment]
@Zanthed Yes, build was successful and was tested on real device running GrapheneOS (except for the webview). I don't think `-ffixed-x18` is needed for Android, quoting LLVM documentation that you linked:
> This generally means that any code that may run on the same thread as code compiled with ShadowCallStack must either target one of the platforms whose ABI reserves x18 (currently Android, Darwin, Fuchsia and Windows) or be compiled with the flag -ffixed-x18.
And we're targetting Android so we don't need `-ffixed-x18`.

**Comment by loryeam** [comment]
I found some websites crashing. I'll investigate the issues.

**Pull request closed without merging**
