### PR TITLE
remove learn more button from the incognito new tab page

### LINKED ISSUE #36: remove or replace learn more link on blank incognito tab

### PR DESCRIPTION
**Pull request by refragable**
Closes #36 

Tested with Vanadium 84.0.4147.111

### CODE REVIEW

**Comment by thestinger** [comment]
Ideally this change would be a lot less invasive such as hiding the link rather than actually removing it to reduce the changes required.

**Comment by refragable** [comment]
I'll take another stab at it then. But editing the html and css in `chrome/browser/resources/ntp4/` didn't seem to affect the incognito new tab page at all.

**Comment by refragable** [comment]
Ready for review again.

* Portait orientation: The "Learn more" link is completely gone. I was not able to see/click it at all.
* Landscape orientation: The "Learn more" link is hidden and there is no text. However, the clickable event still exists (clickable right after "However, downloads and bookmarks will be saved.") Therefore, it's possible (but unlikely) the user could click it and get sent to the web browsing section of the usage page. I believe the patch would need to grow substantially in order to remove it completely.

Tested with Vanadium 84.0.4147.111

**Comment by thestinger** [comment]
I think you should be able to just make it properly hidden / inactive rather than removing the text.

**Comment by refragable** [comment]
Thank you for the forbearance, Daniel. This patch disables both Learn more links in the portrait and landscape incognito new tab pages. There are no invisible links to click on either page.

**Comment by theaeonsolution** [comment]
Hi @refragable, can you please update your branch with the new patches for Vanadium and update your patch number. I'll be testing your pull request this week. Thank you.

**Comment by thestinger** [comment]
@refragable Can you update this for Chromium 85?

**Comment by refragable** [comment]
@thestinger I have rebased to 85.0.4183.81

**Pull request merged**
