### PR TITLE
Apply Chromium's built-in adblocker (subresource filter) to every page

### PR DESCRIPTION
**Pull request by Zoraver**
Addresses #10. Tested in the emulator on a number of webpages and behaved as described below.

The subresource filter does not seem to be applied unless Subresource Filter Rules has a version greater than 0.0.0.0 (visible and updatable on chrome://components). I do not know if Vanadium updates these components automatically; I never observed it in the emulator, but I also never left the emulator running for more than a few minutes at a time. On my own phone running GrapheneOS, I believe that the Subresource Filter Rules component had a valid version, but I manually updated it after and can't remember for sure.

When a site on which ads are being blocked is first loaded, a snackbar appears that states that ads are being blocked. When "more info" is pressed, it says that "this site shows intrusive or misleading ads" and gives the user the option to disable blocking. At first I considered this annoying, but upon further reflection, I decided that it was acceptable, as reimplementing a user interface to allow users to disable blocking for a specific site would be outside the scope of this project.

### CODE REVIEW

**Comment by csagan5** [comment]
@Zoraver I find your approach interesting. Is cloud-based safebrowsing disabled in current Vanadium? Does this type of filtering work without the API calls (for which there is no valid key anyways)?

**Comment by thestinger** [comment]
@Zoraver I don't think it will ever update it automatically without Play Services present, and it'll need to be switched to obtaining it from https://grapheneos.org/. I don't know exactly what this involves doing.

**Comment by thestinger** [comment]
@csagan5 Safe Browsing isn't explicitly disabled but isn't available because the default mode depends on Play Services which isn't present where Vanadium is used, so the Safe Browsing code isn't used. Vanadium is currently only for use within GrapheneOS. I don't want to have Safe Browsing based on Play Services enabled, but I do want to have the option of using the local database implementation. I'm unsure if I would want to have it enabled by default, but I definitely want it as an optional feature. Unfortunately, I couldn't get it working, so I haven't touched this yet. The toggle is currently a no-op since there's no Play Services and it's always effectively disabled. In theory, it should be possible to add an API key for a cloud project with Safe Browsing enabled and use safe_browsing_mode=3 to support Safe Browsing via the local database in the browser. The requests it makes download databases for on truncated hashes (4 bytes) of the URL, but there are other options like simply downloading the entire database, which I don't think is really that large. These requests could also be made to a https://grapheneos.org/ subdomain rather than Google. The same applies to a couple other things like downloading the GPS almanacs.

**Comment by csagan5** [comment]
> Safe Browsing isn't explicitly disabled but isn't available because the default mode depends on Play Services which isn't present where Vanadium is used, so the Safe Browsing code isn't used.

So am I correct to conclude that the built-in adblocker wouldn't work, even with this patch, because of #35?

I have an interest in the built-in adblocker for the reasons explained in https://github.com/GrapheneOS/Vanadium/issues/10#issuecomment-515671578

All things considered it would allow to stay closer to upstream.

**Comment by Zoraver** [comment]
@csagan5 It does work with this patch, as long as the user manually updates the Subresource Filter Rules component.

@thestinger I will look into the component installer / updater later this week to see if I can find a way to change where it obtains components.

**Comment by macchrome** [comment]
https://github.com/chromium/chromium/blob/master/components/subresource_filter/FILTER_LIST_GENERATION.md

**Comment by thestinger** [comment]
It doesn't really need to be filtered though. I'd rather just have the full EasyList / EasyPrivacy as the standard option and alternatives could be offered later.

**Comment by csagan5** [comment]
> The URL that the component updater queries appears to be set in [this file](https://chromium.googlesource.com/chromium/src/+/refs/tags/76.0.3809.111/components/component_updater/component_updater_url_constants.cc).

In Bromite those URLs are already dummied out to `about:blank`; I will start trying your patches for the upcoming v77 release of Bromite.

**Comment by csagan5** [comment]
I have been looking at the format of the subresource filters: https://cs.chromium.org/chromium/src/out/android-Debug/gen/components/url_pattern_index/flat/url_pattern_index_generated.h?l=213

```
 bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_OPTIONS) &&
           VerifyField<uint16_t>(verifier, VT_ELEMENT_TYPES) &&
           VerifyField<uint8_t>(verifier, VT_ACTIVATION_TYPES) &&
           VerifyField<uint8_t>(verifier, VT_URL_PATTERN_TYPE) &&
           VerifyField<uint8_t>(verifier, VT_ANCHOR_LEFT) &&
           VerifyField<uint8_t>(verifier, VT_ANCHOR_RIGHT) &&
           VerifyOffset(verifier, VT_DOMAINS_INCLUDED) &&
           verifier.VerifyVector(domains_included()) &&
           verifier.VerifyVectorOfStrings(domains_included()) &&
           VerifyOffset(verifier, VT_DOMAINS_EXCLUDED) &&
           verifier.VerifyVector(domains_excluded()) &&
           verifier.VerifyVectorOfStrings(domains_excluded()) &&
           VerifyOffset(verifier, VT_URL_PATTERN) &&
           verifier.VerifyString(url_pattern()) &&
           VerifyField<uint32_t>(verifier, VT_ID) &&
           VerifyField<uint32_t>(verifier, VT_PRIORITY) &&
           verifier.EndTable();
  }
};
```

And I found it incredibly familiar. For comparison, this is the top of [Bromite AdBlock engine adblock_entries.h](https://github.com/bromite/bromite/blob/76.0.3809.129/build/filters/adblock_entries.h):

```
#ifndef NET_URL_REQUEST_ADBLOCK_ENTRIES_H_
#define NET_URL_REQUEST_ADBLOCK_ENTRIES_H_

namespace net {

#define ADBLOCK_FLAG_EXCEPTION 1
#define ADBLOCK_FLAG_MATCH_DOMAIN 2
#define ADBLOCK_FLAG_MATCH_BEGIN 4
#define ADBLOCK_FLAG_MATCH_END 8
#define ADBLOCK_FLAG_HAS_WILDCARD 16
#define ADBLOCK_FLAG_HAS_SEPARATOR 32
#define ADBLOCK_FLAG_MATCH_CASE 64
#define ADBLOCK_FLAG_THIRD_PARTY 128
#define ADBLOCK_FLAG_FIRST_PARTY 256
#define ADBLOCK_FLAG_RESOURCE_TYPE_IN 512
#define ADBLOCK_FLAG_RESOURCE_TYPE_NOT_IN 1024
#define ADBLOCK_FLAG_RT_STYLESHEET 131072
#define ADBLOCK_FLAG_RT_SCRIPT 196608
#define ADBLOCK_FLAG_RT_IMAGE 262144
#define ADBLOCK_FLAG_RT_MEDIA 327680
#define ADBLOCK_FLAG_RT_XHR 851968
#define ADBLOCK_FLAG_RT_PING 917504
#define ADBLOCK_FLAG_RT_CSP_REPORT 1048576

struct adblock_entry {
  const char **matches;
  int flags;
  const char **domains, **domains_skip;
};
```

For those not familiar with the Bromite/NoChromo engine, it uses anchors and I personally added the domains whitelist/blacklist feature which was not present in the original NoChromo engine.

You can see how anchors work here: https://github.com/bromite/bromite/blob/76.0.3809.129/build/patches/Bromite-adblock-engine.patch#L596

To me it looks like a better/tidier implementation of the engine which is used in Bromite, but I cannot claim much: there might be prior art which I am not aware of.

Just the combination of anchors and domains whitelist/blacklist is something that I immediately recognised, together with the [recently added resource-type-based flags (also a new feature I added on top of original NoChromo version)](https://github.com/bromite/bromite/issues/115).

This also means that the native engine used in Chromium is not that different from Bromite's one, and switching to it should be easier.

I will most likely start with a hard-coded block of filters, but I would not be surprised if converting Bromite adblock filters to the subresource filters is a 1:1 operation (given all the above considerations) and thus also easier to integrate with a custom URL download functionality.

**Comment by csagan5** [comment]
@Zoraver does the enabled update in 89768a842466935c84cdd983cf2ca89386b94b85 work?

I am currently experimenting with a dedicated AdBlockUpdater that does not use components.

**Comment by Zoraver** [comment]
@csagan5 It does, but it should be considered as a temporary solution that can be replaced by a better one if or when one is developed. Essentially, the patch causes Vanadium to check for updates to the Subresource Filter Rules component each time the browser is started. When GrapheneOS starts to ship its own version of this component, the id being passed to `OnDemandUpdate()` will need to be updated.

**Comment by csagan5** [comment]
I see; I am currently developing a dedicated filters update service, I will eventually release it as part of next Bromite release if I get it working.

**Comment by csagan5** [comment]
@Zoraver the update service is almost complete, I am testing it now.

I am thinking about how to provide an UI option to specify the filters URL. Would you be interested in developing it? My best pick would be to copy https://cs.chromium.org/chromium/src/chrome/android/java/src/org/chromium/chrome/browser/preferences/HomepageEditor.java, make it accessible from settings and add a new profile preference for it.

**Comment by Zoraver** [comment]
@csagan5 I would be happy to, but I am not sure if I will have time to work on it until next week.

**Comment by csagan5** [comment]
Quoting self for context:
> So am I correct to conclude that the built-in adblocker wouldn't work, even with this patch, because of #35?
> 
> I have an interest in the built-in adblocker for the reasons explained in [#10 (comment)](https://github.com/GrapheneOS/Vanadium/issues/10#issuecomment-515671578)

I have figured out that in current Chromium version (v77) enabled presets/configurations are only used in coordination with SafeBrowsing, see calls to `ActivationStateComputingNavigationThrottle::NotifyPageActivationWithRuleset`.

This method is called either via the full SafeBrowsing throttle chain, or when the `kAdTagging` feature is enabled by default. This is a feature enabled to measure the impact of the ad filter on 1% of traffic of all users, as if it were enabled on all sites.

They are clearly testing what would be the impact in performance; since in Bromite I have completely disabled SafeBrowsing, I must avoid going through the SafeBrowsing throttle chain. I understand how Vanadium might differ here, but I am reporting my findings as they might be useful anyways.

So for now I am experimenting with calling `ActivationStateComputingNavigationThrottle::NotifyPageActivationWithRuleset` as the ad tagging feature does, for all sites (but with real filtering consequences).

**Comment by csagan5** [comment]
The patch for the Bromite AdBlockerUpdate service is released: https://github.com/bromite/bromite/blob/master/build/patches/Bromite-AdBlockUpdaterService.patch

@Zoraver I included your 2 patches from here as well, as separate patches, although they are unnecessary and might remove them in the future - they are only relevant if SafeBrowsing is being built in.

**Comment by csagan5** [comment]
> although they are unnecessary and might remove them in the future - they are only relevant if SafeBrowsing is being built in.

Correction: the patch to hide the ads popup works also without SafeBrowsing, so I will keep that one

**Comment by thestinger** [comment]
So does https://github.com/bromite/bromite/blob/master/build/patches/Bromite-AdBlockUpdaterService.patch work as a standalone patch, or are there some other dependencies?

Do you know how this interacts with having the Safe Browsing feature built in? I'm curious about this part:

> I included your 2 patches from here as well, as separate patches, although they are unnecessary and might remove them in the future - they are only relevant if SafeBrowsing is being built in.

Since it implies that they interact together and I'm not entirely clear on what happens in that case. You're a lot more familiar with all of this blocking and Safe Browsing code at this point.

**Comment by csagan5** [comment]
> You're a lot more familiar with all of this blocking and Safe Browsing code at this point.

With Safe Browsing my experience is of the "destructive" type, as I have tried to disable it at all costs over the major releases and currently the patch holds, although it is cumbersome so it is not a position I really like to be in regarding patch maintenance. [Such patch](https://github.com/bromite/bromite/blob/77.0.3865.95/build/patches/Disable-safe-browsing.patch) was originally based on the ungoogled-chromium patch, but it might have differed sensibly by now as I have always built it only for Android (it needed extra changes for such target since the very beginning).

I will explain a bit the interaction between the Subresource filter and Safe Browsing, as I understood it (although some drawing would be better):

* in current Chromium subresource filtering happens through safe browsing, although the two at some point were more independent (as I have written before, they start to entangle further in v77)
* in current Chromium there is however "AdTagging", which happens independently of safe browsing being even compiled in or not, and this ad tagging is basically a dry-run of the subresource filters on 1% of **all** pages for metrics collections reasons (see [this comment](https://github.com/GrapheneOS/Vanadium/pull/42#issuecomment-531554933))

The way subresource filtering happens in safe browsing is through "presets", so what I mentioned before in [this comment](https://github.com/GrapheneOS/Vanadium/pull/42#issuecomment-531660666), then corrected in [this comment](https://github.com/GrapheneOS/Vanadium/pull/42#issuecomment-535990689), is relevant only for the [presets patches](https://github.com/GrapheneOS/Vanadium/pull/42/commits/0625e813daf4fb16b429707eea8bf615098bec4b#diff-0745d9dab4921bdb92fc63067ea3b6cc) and not the ads popup patch.

Basically @Zoraver has efficiently enabled the filter for all pages by using the same mechanism used in Safe browsing, which is by adding a new preset.

However in Bromite Safe browsing has been historically always disabled because of the tight coupling with the server-side part, so I had to go another route (after testing myself around presets) which is by giving a different purpose to the "ad tagging" feature and making it effective instead of a dry-run. This works fine because as I mentioned before ad tagging is independent of safe browsing.

The [AdBlockUpdaterService patch](https://github.com/bromite/bromite/blob/77.0.3865.95/build/patches/Bromite-AdBlockUpdaterService.patch) covers two purposes:
* provide a filters update mechanism that does not need download of a component/extension, and replace it for the subresource filter (it uses a simple HTTPS GET request and evaluates Last-Modified header to create a version)
* activate subresource filter similarly to ad tagging, bypassing the need to go through Safe browsing and presets

For Vanadium if you want to continue building with Safe browsing (suggested, since the safe-browsing-disabling patch is a burden) you need only (1) and not (2), although the patch as-is would work if you avoid also adding the presets patches from @Zoraver (otherwise double filtering might happen, not sure).

The silver lining here as you can sense is that upstream is making ad-blocking in the same realm as security/safety, and very close to "report home X was blocked" functionality; I do not agree with this strategy.

I can assist you with the integration of this patch if you need to split (1) from (2); I also have a patch laying around that add log lines to understand better how the presets work.

**Comment by thestinger** [comment]
@Zoraver I'm still very interested in this feature but I lack the time / energy to work on advancing it myself. Let me know if you plan to work on this again in the near future and I can make some time available to discuss / review the approach.

**Comment by thestinger** [comment]
Going to close this PR since it will need to be reopened but this feature is definitely welcome, and I just didn't want to land it in the form of using the upstream filter component.

**Pull request closed without merging**
