### PR TITLE
Recolor logos used in chrome://version

### PR DESCRIPTION
**Pull request by refragable**
https://github.com/GrapheneOS/Vanadium/issues/30

Hi,

I've desaturated the Chromium logos used in the version page using the same command as the Vanadium branding patch. The png files have been optimized with `tools/resources/optimize-png-files.sh`.

Let me know if I need to remove the "chromium" in the image or if I need to use the unoptimized png to make this patch acceptable.

Tested working on Pixel 4.

Vanadium

Vanadium-darkmode

### CODE REVIEW

**Comment by thestinger** [comment]
I think the logo would need to be replaced rather than just recolored, since this still refers to Chromium rather than Vanadium. I don't think this page is directly accessible via the UI anymore, so perhaps it isn't worth doing this anymore. It's one more thing that will need to be ported between each version and might occasionally hit conflicts. I think I'll just be closing the issue and not changing this after all.

**Comment by thestinger** [comment]
@refragable A patch *removing* the logo probably makes more sense.

**Comment by thestinger** [comment]
Changed https://github.com/GrapheneOS/Vanadium/issues/30 to refer to removing it. It's too much trouble to make a new one referring to Vanadium. If removing it is very simple and uninvasive, might as well do that. If it's too much trouble, then it's not worth it.

**Comment by refragable** [comment]
> Changed #30 to refer to removing it. It's too much trouble to make a new one referring to Vanadium. If removing it is very simple and uninvasive, might as well do that. If it's too much trouble, then it's not worth it.

I believe a patch to remove the logo would only involve editing the `about_version` html template. I'll work on a new pull request.

**Comment by thestinger** [comment]
It's a really low resolution / ugly logo anyway so I think that's best.

**Pull request closed without merging**
