### PR TITLE
Implement UI for JIT Site Settings

### PR DESCRIPTION
**Pull request by quh4gko8**
This PR fully integrates [JIT policies](https://source.chromium.org/chromium/chromium/src/+/dc80798acb4bf6165ae9ff4d6b22ed8f9ddc0bf2) into the per-site (eTLD) setting, which works when strict origin isolation (StrictOriginIsolation) and strict site isolation (SitePerProcees) are enabled, otherwise the renderer process will be shared at eTLD+1.

### CODE REVIEW

**Comment by uazo** [comment]
you've also made exception behave as if the user enters `* .site.com` regardless of user input.
pure curiosity, can I ask you why?

**Comment by quh4gko8** [comment]
> 

The underlying policy for JIT setting is per-domain, as of this [commit](https://source.chromium.org/chromium/chromium/src/+/2f439d0d5102096da3f852d71ac37412d989ac66)

**Comment by quh4gko8** [comment]
The per-domain JIT setting will load in if the domain `ContentSettingException` is loaded. However, only setting the domain site setting causes UI inconsistency, so it has to be also set for `*.site.com`, preloading it whenever `SingleWebsiteSettings` is opened from page info, or from All Sites

**Comment by uazo** [comment]
> The underlying policy for JIT setting is per-domain, as of this commit

I understand that the commit explicitly speaks of windows

```
When running in
interpreted mode the sandbox policy on Windows can subsequently be
tightened to prevent creation of any new executable pages.
...
Since Site Isolation is the base primitive here, any JIT policy can
only be applied on a site-by-site basis, restricting the policy to
eTLD+1 granularity.
```

theoretically in android, if the renderprocess does not have the suitable jit configuration, another one is created [source](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/renderer_host/render_process_host_impl.cc;l=504;drc=60124005e97ae2716b0fb34187d82da6019b571f;bpv=1;bpt=1)
this again theoretically would allow me to have different exceptions between `source.chromium.org` and `www.chromium.org`, for example.
maybe I'm wrong... I'll try

**Comment by quh4gko8** [comment]
Initial attempt to just simply adding JIT site setting like adding back autoplay did not work, nonetheless more testing, feedback will be helpful

**Comment by quh4gko8** [comment]
> > The underlying policy for JIT setting is per-domain, as of this commit
> 
> I understand that the commit explicitly speaks of windows
> 
> ```
> When running in
> interpreted mode the sandbox policy on Windows can subsequently be
> tightened to prevent creation of any new executable pages.
> ...
> Since Site Isolation is the base primitive here, any JIT policy can
> only be applied on a site-by-site basis, restricting the policy to
> eTLD+1 granularity.
> ```
> 
> theoretically in android, if the renderprocess does not have the suitable jit configuration, another one is created [source](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/renderer_host/render_process_host_impl.cc;l=504;drc=60124005e97ae2716b0fb34187d82da6019b571f;bpv=1;bpt=1) this again theoretically would allow me to have different exceptions between `source.chromium.org` and `www.chromium.org`, for example. maybe I'm wrong... I'll try

Android support in this [other commit](https://source.chromium.org/chromium/chromium/src/+/dc80798acb4bf6165ae9ff4d6b22ed8f9ddc0bf2) didn't seem to touch that part for some reason

**Comment by quh4gko8** [comment]
> > The underlying policy for JIT setting is per-domain, as of this commit
> 
> I understand that the commit explicitly speaks of windows
> 
> ```
> When running in
> interpreted mode the sandbox policy on Windows can subsequently be
> tightened to prevent creation of any new executable pages.
> ...
> Since Site Isolation is the base primitive here, any JIT policy can
> only be applied on a site-by-site basis, restricting the policy to
> eTLD+1 granularity.
> ```
> 
> theoretically in android, if the renderprocess does not have the suitable jit configuration, another one is created [source](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/renderer_host/render_process_host_impl.cc;l=504;drc=60124005e97ae2716b0fb34187d82da6019b571f;bpv=1;bpt=1) this again theoretically would allow me to have different exceptions between `source.chromium.org` and `www.chromium.org`, for example. maybe I'm wrong... I'll try

Thanks for pointing it out, it works fine per-site, there was an error in initial bringup on thsi patch

Feel free to use this on Bromite

**Comment by quh4gko8** [comment]
Merge with #154 for better user experience

**Comment by quh4gko8** [comment]
updated for v99

**Comment by thestinger** [comment]
@cdesai This code was written by a GrapheneOS project member and we expect you to remove it and the other code taken from us from Calyx. Laundering our code through Bromite doesn't change the fact that it came from us, and you aren't even respecting the license. I hope you also realize that shipping a GPLv3 WebView is a GPLv3 violation and there are multiple people with their code in Bromite who are willing to assign copyright to me so that I can take legal action against you based on it. You cannot just take GPLv3 code and put it into non-GPLv3-compatible apps as part of your OS. Vanadium has an exception permitting this, Bromite does not.

**Comment by thestinger** [comment]
@cdesai Sorry, wrong user.

**Comment by thestinger** [comment]
@chirayudesai This code was written by a GrapheneOS project member and we expect you to remove it and the other code taken from us from Calyx. Laundering our code through Bromite doesn't change the fact that it came from us, and you aren't even respecting the license. I hope you also realize that shipping a GPLv3 WebView is a GPLv3 violation and there are multiple people with their code in Bromite who are willing to assign copyright to me so that I can take legal action against you based on it. You cannot just take GPLv3 code and put it into non-GPLv3-compatible apps as part of your OS. Vanadium has an exception permitting this, Bromite does not.

**Comment by quh4gko8** [comment]
> @chirayudesai This code was written by a GrapheneOS project member and we expect you to remove it and the other code taken from us from Calyx. Laundering our code through Bromite doesn't change the fact that it came from us, and you aren't even respecting the license. I hope you also realize that shipping a GPLv3 WebView is a GPLv3 violation and there are multiple people with their code in Bromite who are willing to assign copyright to me so that I can take legal action against you based on it. You cannot just take GPLv3 code and put it into non-GPLv3-compatible apps as part of your OS. Vanadium has an exception permitting this, Bromite does not.

Patch author here, and I expect this patch to be removed by @chirayudesia from Calyx, as I only permitted its usage in Bromite in the particular exchange of comversation. I do not permit it to be used for Calyx institute and any projects that support them in misleading users on what they offer on privacy and security, and expending users' donations on using others' changes without proper attribution, even not providing updates in timely manner in their software and OS alike, unless somebody notices.

**Comment by quh4gko8** [comment]
> @chirayudesai This code was written by a GrapheneOS project member and we expect you to remove it and the other code taken from us from Calyx. Laundering our code through Bromite doesn't change the fact that it came from us, and you aren't even respecting the license. I hope you also realize that shipping a GPLv3 WebView is a GPLv3 violation and there are multiple people with their code in Bromite who are willing to assign copyright to me so that I can take legal action against you based on it. You cannot just take GPLv3 code and put it into non-GPLv3-compatible apps as part of your OS. Vanadium has an exception permitting this, Bromite does not.

Patch author here, and I do not appreciate using my patch, through Bromite, especially that I mentioned in particular here was only given permission for Bromite usage at that time. I do not permit it, and future patches written by me to be used for Calyx institute and any projects that support them in misleading users on what they offer on privacy and security, and expending, wasting users' donations on using others' patches without proper attribution and testing, even giving updates in untimely, delayed manner in their software and OS alike, unless it is for public relation show.

**Pull request closed without merging**
