### PR TITLE
don't permit user installed certificates

### PR DESCRIPTION
**Pull request by Flex1911**

### CODE REVIEW

**Comment by csagan5** [comment]
@Flex1911 I have added your patch in Bromite here: https://github.com/bromite/bromite/blob/88.0.4324.149/build/patches/Do-not-permit-user-installed-certificates.patch

**Comment by thestinger** [comment]
I'm not sure that I want to remove this.

**Comment by thestinger** [comment]
It might be better just to show a warning when it's being used.

**Comment by Flex1911** [comment]
Thanks for your response.
I guess that's a very specific situation so I'm going to keep the patch for my internal use only.

**Comment by csagan5** [comment]
@thestinger the patch that Bromite now uses is this: https://github.com/bromite/bromite/blob/90.0.4430.92/build/patches/Add-AllowUserCertificates-flag.patch

It adds a flag to allow user certificates, disabled by default (thanks to @uazo for developing it).

**Pull request closed without merging**
