### PR TITLE
Disable V8 JIT

### PR DESCRIPTION
**Pull request by Zoraver**
I have successfully built and run Vanadium with this patch. Performance-wise, I observed a ~25% decrease on Speedometer 2.0, but did not notice a meaningful difference when viewing several relatively js-heavy web pages.

### CODE REVIEW

**Comment by csagan5** [comment]
@Zoraver what is the rationale to disable it? Is it something you guys have discussed privately or on Discord?

I assume you want to disable it because more vulnerabilities are expected to be found there.

**Comment by Zoraver** [comment]
@csagan5 Disabling V8 JIT was mentioned in passing on Matrix a few weeks ago, and I thought it would be interesting to see whether it could be disabled on Vanadium. JIT requires the runtime allocation of executable memory; disabling it should reduce the attack surface of the browser. This could also allow a more restrictive SELinux policy to be applied to Vanadium.

Ultimately, it will be up to Daniel to decide if the loss in performance is worth it.

**Comment by thestinger** [comment]
@Zoraver Can you test if this also gets applied for the WebView? It should probably be changed for both if the decision is to change this. I'm unsure if these are shared flags for both the browser and WebView content or just the browser.

**Comment by thestinger** [comment]
@csagan5 The JIT compiler adds a lot of attack surface / complexity and also requires violating the standard w^x policy enforced for most of the base system on GrapheneOS via SELinux policy. It's enforced for the standard untrusted app sandbox only for apps signed with OS signing keys. We'll need to expand it to the rest of the base OS and figure out a system for deploying it with third party apps. You can see those changes in https://github.com/GrapheneOS/platform_system_sepolicy. The `execmem` policy is what allows apps to allocate memory that's `rwx` or to transition from memory that was at one point writable to executable. Disallowing execmem gets rid of dynamic native code via anonymous mappings and then the removal of execute for tmpfs, ashmem and app_data_file closes the other ways of doing it via non-anonymous mappings or the file system.

**Comment by thestinger** [comment]
So, separately from vulnerabilities in the JIT compiler, it's also fundamentally opposed to security properties that we want to have including globally disallowing any dynamic native code from being run by any component in the base system. The Chromium JIT compiler is the only case of violating that policy in practice, but enforcing the rules for the entire base system requires more work than just getting rid of this last case. SELinux policy will need to be adjusted to make sure everything is either in the split untrusted / isolated app domains created for the base system or new domains appropriate for components that we want to be able to update out-of-band.

For the base system, we're also forbidding executing native code from userdata, which is a requirement for apps with native code receiving updates. This goes beyond just the benefits of w^x for mitigating file / memory write vulnerabilities and also gets into verified boot security. Out-of-band updates to base system apps can be verified on boot for the apk itself based on the signature but libraries extracted from it won't get verified and neither will the compiled odex code created from the dex bytecode in the apk. Ideally, it would be shipped with the apk in a form that can be verified. That's implemented for APEX components but apps are a different story.

There's a lot of work that has to be done in these two areas. Some of the work is getting slowly done upstream but they're many years away from finishing the basics, and there's a whole lot more to do beyond that since this can be extended beyond native code.

https://github.com/GrapheneOS/os_issue_tracker/issues/33

**Comment by Zoraver** [comment]
@thestinger I just ran a test using the WebView Log Verbosifier and it does get applied to the WebView.

Tracing the Chromium source code:
AwBrowserProcess.java - `start()` ->
BrowserStartupControllerImpl.java - `startBrowserProcessesSync()` -> `prepareToStartBrowserProcess()` ->
browser_startup_controller.cc - `JNI_BrowserStartupControllerImpl_SetCommandLineFlags()` ->
content_startup_flags.cc - `SetContentCommandLineFlags()`

**Comment by csagan5** [comment]
> we're also forbidding executing native code from userdata

I was expecting this to be already in upstream Android...

Thanks for the explanation @Zoraver @thestinger; I have read a bit about it on [other discussions](https://github.com/termux/termux-app/issues/1072#issuecomment-599252674) and it is indeed interesting.

**Comment by thestinger** [comment]
This is currently too aggressive and I think it would be best to add this as an option first and then consider changing the default later. Vanadium also currently gets treated as a third party app via SELinux policy anyway due to not special casing the signing key it uses.

**Comment by thestinger** [comment]
I opened #67 about this.

**Pull request closed without merging**
